//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Proekt4
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Справ дол.
    /// </summary>
    // *** Start programmer edit section *** (СправДол CustomAttributes)

    // *** End programmer edit section *** (СправДол CustomAttributes)
    [AutoAltered()]
    [Caption("Справочник Должности")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("СправДолE", new string[] {
            "Должность as \'Должность\'"})]
    [View("СправДолL", new string[] {
            "Должность as \'Должность\'"})]
    public class СправДол : ICSSoft.STORMNET.DataObject
    {
        
        private string fДолжность;
        
        // *** Start programmer edit section *** (СправДол CustomMembers)

        // *** End programmer edit section *** (СправДол CustomMembers)

        
        /// <summary>
        /// Должность.
        /// </summary>
        // *** Start programmer edit section *** (СправДол.Должность CustomAttributes)

        // *** End programmer edit section *** (СправДол.Должность CustomAttributes)
        [StrLen(255)]
        public virtual string Должность
        {
            get
            {
                // *** Start programmer edit section *** (СправДол.Должность Get start)

                // *** End programmer edit section *** (СправДол.Должность Get start)
                string result = this.fДолжность;
                // *** Start programmer edit section *** (СправДол.Должность Get end)

                // *** End programmer edit section *** (СправДол.Должность Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (СправДол.Должность Set start)

                // *** End programmer edit section *** (СправДол.Должность Set start)
                this.fДолжность = value;
                // *** Start programmer edit section *** (СправДол.Должность Set end)

                // *** End programmer edit section *** (СправДол.Должность Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "СправДолE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View СправДолE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("СправДолE", typeof(IIS.Proekt4.СправДол));
                }
            }
            
            /// <summary>
            /// "СправДолL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View СправДолL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("СправДолL", typeof(IIS.Proekt4.СправДол));
                }
            }
        }
    }
}
