//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Proekt4
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Справ клас.
    /// </summary>
    // *** Start programmer edit section *** (СправКлас CustomAttributes)

    // *** End programmer edit section *** (СправКлас CustomAttributes)
    [AutoAltered()]
    [Caption("Справочник Классы")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("СправКласE", new string[] {
            "Классы as \'Классы\'"})]
    [View("СправКласL", new string[] {
            "Классы as \'Классы\'"})]
    public class СправКлас : ICSSoft.STORMNET.DataObject
    {
        
        private string fКлассы;
        
        // *** Start programmer edit section *** (СправКлас CustomMembers)

        // *** End programmer edit section *** (СправКлас CustomMembers)

        
        /// <summary>
        /// Классы.
        /// </summary>
        // *** Start programmer edit section *** (СправКлас.Классы CustomAttributes)

        // *** End programmer edit section *** (СправКлас.Классы CustomAttributes)
        [StrLen(255)]
        public virtual string Классы
        {
            get
            {
                // *** Start programmer edit section *** (СправКлас.Классы Get start)

                // *** End programmer edit section *** (СправКлас.Классы Get start)
                string result = this.fКлассы;
                // *** Start programmer edit section *** (СправКлас.Классы Get end)

                // *** End programmer edit section *** (СправКлас.Классы Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (СправКлас.Классы Set start)

                // *** End programmer edit section *** (СправКлас.Классы Set start)
                this.fКлассы = value;
                // *** Start programmer edit section *** (СправКлас.Классы Set end)

                // *** End programmer edit section *** (СправКлас.Классы Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "СправКласE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View СправКласE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("СправКласE", typeof(IIS.Proekt4.СправКлас));
                }
            }
            
            /// <summary>
            /// "СправКласL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View СправКласL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("СправКласL", typeof(IIS.Proekt4.СправКлас));
                }
            }
        }
    }
}
