//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Proekt4
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Справ сотр.
    /// </summary>
    // *** Start programmer edit section *** (СправСотр CustomAttributes)

    // *** End programmer edit section *** (СправСотр CustomAttributes)
    [AutoAltered()]
    [Caption("Справочник Сотрудники")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("СправСотрE", new string[] {
            "ФИОСотр as \'Сотрудник\'",
            "СправДол as \'Должность\'",
            "СправДол.Должность as \'Нет\'",
            "Кабинет as \'Кабинет\'"})]
    [View("СправСотрL", new string[] {
            "ФИОСотр as \'Сотрудник\'",
            "СправДол.Должность as \'Нет\'",
            "Кабинет as \'Кабинет\'"})]
    public class СправСотр : ICSSoft.STORMNET.DataObject
    {
        
        private string fФИОСотр;
        
        private string fКабинет;
        
        private IIS.Proekt4.СправДол fСправДол;
        
        // *** Start programmer edit section *** (СправСотр CustomMembers)

        // *** End programmer edit section *** (СправСотр CustomMembers)

        
        /// <summary>
        /// Кабинет.
        /// </summary>
        // *** Start programmer edit section *** (СправСотр.Кабинет CustomAttributes)

        // *** End programmer edit section *** (СправСотр.Кабинет CustomAttributes)
        [StrLen(255)]
        public virtual string Кабинет
        {
            get
            {
                // *** Start programmer edit section *** (СправСотр.Кабинет Get start)

                // *** End programmer edit section *** (СправСотр.Кабинет Get start)
                string result = this.fКабинет;
                // *** Start programmer edit section *** (СправСотр.Кабинет Get end)

                // *** End programmer edit section *** (СправСотр.Кабинет Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (СправСотр.Кабинет Set start)

                // *** End programmer edit section *** (СправСотр.Кабинет Set start)
                this.fКабинет = value;
                // *** Start programmer edit section *** (СправСотр.Кабинет Set end)

                // *** End programmer edit section *** (СправСотр.Кабинет Set end)
            }
        }
        
        /// <summary>
        /// ФИОСотр.
        /// </summary>
        // *** Start programmer edit section *** (СправСотр.ФИОСотр CustomAttributes)

        // *** End programmer edit section *** (СправСотр.ФИОСотр CustomAttributes)
        [StrLen(255)]
        public virtual string ФИОСотр
        {
            get
            {
                // *** Start programmer edit section *** (СправСотр.ФИОСотр Get start)

                // *** End programmer edit section *** (СправСотр.ФИОСотр Get start)
                string result = this.fФИОСотр;
                // *** Start programmer edit section *** (СправСотр.ФИОСотр Get end)

                // *** End programmer edit section *** (СправСотр.ФИОСотр Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (СправСотр.ФИОСотр Set start)

                // *** End programmer edit section *** (СправСотр.ФИОСотр Set start)
                this.fФИОСотр = value;
                // *** Start programmer edit section *** (СправСотр.ФИОСотр Set end)

                // *** End programmer edit section *** (СправСотр.ФИОСотр Set end)
            }
        }
        
        /// <summary>
        /// Справ сотр.
        /// </summary>
        // *** Start programmer edit section *** (СправСотр.СправДол CustomAttributes)

        // *** End programmer edit section *** (СправСотр.СправДол CustomAttributes)
        [PropertyStorage(new string[] {
                "СправДол"})]
        [NotNull()]
        public virtual IIS.Proekt4.СправДол СправДол
        {
            get
            {
                // *** Start programmer edit section *** (СправСотр.СправДол Get start)

                // *** End programmer edit section *** (СправСотр.СправДол Get start)
                IIS.Proekt4.СправДол result = this.fСправДол;
                // *** Start programmer edit section *** (СправСотр.СправДол Get end)

                // *** End programmer edit section *** (СправСотр.СправДол Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (СправСотр.СправДол Set start)

                // *** End programmer edit section *** (СправСотр.СправДол Set start)
                this.fСправДол = value;
                // *** Start programmer edit section *** (СправСотр.СправДол Set end)

                // *** End programmer edit section *** (СправСотр.СправДол Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "СправСотрE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View СправСотрE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("СправСотрE", typeof(IIS.Proekt4.СправСотр));
                }
            }
            
            /// <summary>
            /// "СправСотрL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View СправСотрL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("СправСотрL", typeof(IIS.Proekt4.СправСотр));
                }
            }
        }
    }
}
